package com.example.mvpdemo0602.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.mvpdemo0602.bean.Persion;

import com.example.mvpdemo0602.greendao.PersionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig persionDaoConfig;

    private final PersionDao persionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        persionDaoConfig = daoConfigMap.get(PersionDao.class).clone();
        persionDaoConfig.initIdentityScope(type);

        persionDao = new PersionDao(persionDaoConfig, this);

        registerDao(Persion.class, persionDao);
    }
    
    public void clear() {
        persionDaoConfig.clearIdentityScope();
    }

    public PersionDao getPersionDao() {
        return persionDao;
    }

}
